services:
  scanner-webhook:
    build: .
    image: karmora-scanner-webhook:latest
    container_name: karmora-scanner-webhook
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3001"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=bridge"
      - "traefik.http.routers.karmora-scanner.rule=Host(`scanner.karmora.com`)"
      - "traefik.http.routers.karmora-scanner.entrypoints=websecure"
      - "traefik.http.routers.karmora-scanner.tls.certresolver=letsencrypt"
      - "traefik.http.services.karmora-scanner.loadbalancer.server.port=3001"
